"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-06-10 14:50:21.624718

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op
from app.models.sentinels import UNKNOWN_DISPLAY_NAME, UNKNOWN_NORMALIZED_NAME

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "authors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("normalized_name", sa.String(length=500), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_authors_normalized_name"), "authors", ["normalized_name"], unique=True)
    op.create_table(
        "ingestion_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_file", sa.String(length=500), nullable=False),
        sa.Column("file_hash", sa.String(length=64), nullable=False),
        sa.Column("staged_path", sa.String(length=1000), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("total_lines", sa.Integer(), nullable=True),
        sa.Column("raw_loaded_count", sa.Integer(), nullable=True),
        sa.Column("skipped_count", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ingestion_runs_file_hash"),
        "ingestion_runs",
        ["file_hash"],
        unique=False,
    )
    op.create_index(op.f("ix_ingestion_runs_status"), "ingestion_runs", ["status"], unique=False)
    op.create_table(
        "organizations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("normalized_name", sa.String(length=500), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_organizations_normalized_name"),
        "organizations",
        ["normalized_name"],
        unique=True,
    )
    op.create_table(
        "tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tags_name"), "tags", ["name"], unique=True)
    op.create_table(
        "ingestion_errors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("line_number", sa.Integer(), nullable=False),
        sa.Column("raw_line", sa.Text(), nullable=False),
        sa.Column("error_category", sa.String(length=20), nullable=False),
        sa.Column("error_detail", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["run_id"], ["ingestion_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ingestion_errors_run_id"), "ingestion_errors", ["run_id"], unique=False
    )
    op.create_table(
        "raw_documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ingestion_run_id", sa.Integer(), nullable=False),
        sa.Column("line_number", sa.Integer(), nullable=False),
        sa.Column("raw_data", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("normalized_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["ingestion_run_id"], ["ingestion_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_raw_documents_ingestion_run_id"),
        "raw_documents",
        ["ingestion_run_id"],
        unique=False,
    )
    op.create_index(op.f("ix_raw_documents_status"), "raw_documents", ["status"], unique=False)
    op.create_table(
        "documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("raw_document_id", sa.Integer(), nullable=False),
        sa.Column("raw_external_id", sa.String(length=255), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("normalized_title", sa.String(length=500), nullable=True),
        sa.Column("abstract", sa.Text(), nullable=True),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("published_at", sa.Date(), nullable=True),
        sa.Column("published_at_raw", sa.String(length=100), nullable=True),
        sa.Column("updated_at", sa.Date(), nullable=True),
        sa.Column("updated_at_raw", sa.String(length=100), nullable=True),
        sa.Column("source_name", sa.String(length=255), nullable=True),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("language", sa.String(length=20), nullable=False),
        sa.Column("language_raw", sa.String(length=100), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("status_raw", sa.String(length=100), nullable=True),
        sa.Column("document_type", sa.String(length=30), nullable=False),
        sa.Column("document_type_raw", sa.String(length=100), nullable=True),
        sa.Column("region", sa.String(length=100), nullable=True),
        sa.Column("url", sa.String(length=1000), nullable=True),
        sa.Column("url_valid", sa.Boolean(), nullable=True),
        sa.Column("doi", sa.String(length=255), nullable=True),
        sa.Column("doi_valid", sa.Boolean(), nullable=True),
        sa.Column("citation_count", sa.Integer(), nullable=True),
        sa.Column("word_count", sa.Integer(), nullable=True),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("relevance_score", sa.Float(), nullable=True),
        sa.Column("version", sa.String(length=50), nullable=True),
        sa.Column("open_access", sa.Boolean(), nullable=True),
        sa.Column("open_access_raw", sa.String(length=100), nullable=True),
        sa.Column("peer_reviewed", sa.Boolean(), nullable=True),
        sa.Column("peer_reviewed_raw", sa.String(length=100), nullable=True),
        sa.Column("duplicate_group_id", sa.Integer(), nullable=True),
        sa.Column("is_canonical", sa.Boolean(), nullable=True),
        sa.Column("duplicate_confidence", sa.Float(), nullable=True),
        sa.Column("quality_score", sa.Float(), nullable=True),
        sa.Column("normalization_warnings", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["authors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(["raw_document_id"], ["raw_documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_documents_document_type"), "documents", ["document_type"], unique=False
    )
    op.create_index(
        op.f("ix_documents_duplicate_group_id"),
        "documents",
        ["duplicate_group_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_documents_normalized_title"),
        "documents",
        ["normalized_title"],
        unique=False,
    )
    op.create_index(
        "ix_documents_normalized_title_duplicate_group_id",
        "documents",
        ["normalized_title", "duplicate_group_id"],
        unique=False,
    )
    op.create_index(op.f("ix_documents_published_at"), "documents", ["published_at"], unique=False)
    op.create_index(
        op.f("ix_documents_quality_score"), "documents", ["quality_score"], unique=False
    )
    op.create_index(
        op.f("ix_documents_raw_document_id"),
        "documents",
        ["raw_document_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_documents_raw_external_id"),
        "documents",
        ["raw_external_id"],
        unique=False,
    )
    op.create_index(op.f("ix_documents_region"), "documents", ["region"], unique=False)
    op.create_index(op.f("ix_documents_status"), "documents", ["status"], unique=False)
    op.create_index(
        "ix_documents_status_document_type",
        "documents",
        ["status", "document_type"],
        unique=False,
    )
    op.create_table(
        "document_tags",
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("document_id", "tag_id"),
    )
    # ### end Alembic commands ###

    # Seed shared "Unknown" sentinel rows used when author/organization names are missing or junk.
    for table_name in ("authors", "organizations"):
        op.bulk_insert(
            sa.table(
                table_name,
                sa.column("name", sa.String),
                sa.column("normalized_name", sa.String),
            ),
            [
                {
                    "name": UNKNOWN_DISPLAY_NAME,
                    "normalized_name": UNKNOWN_NORMALIZED_NAME,
                }
            ],
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("document_tags")
    op.drop_index("ix_documents_status_document_type", table_name="documents")
    op.drop_index(op.f("ix_documents_status"), table_name="documents")
    op.drop_index(op.f("ix_documents_region"), table_name="documents")
    op.drop_index(op.f("ix_documents_raw_external_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_raw_document_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_quality_score"), table_name="documents")
    op.drop_index(op.f("ix_documents_published_at"), table_name="documents")
    op.drop_index("ix_documents_normalized_title_duplicate_group_id", table_name="documents")
    op.drop_index(op.f("ix_documents_normalized_title"), table_name="documents")
    op.drop_index(op.f("ix_documents_duplicate_group_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_document_type"), table_name="documents")
    op.drop_table("documents")
    op.drop_index(op.f("ix_raw_documents_status"), table_name="raw_documents")
    op.drop_index(op.f("ix_raw_documents_ingestion_run_id"), table_name="raw_documents")
    op.drop_table("raw_documents")
    op.drop_index(op.f("ix_ingestion_errors_run_id"), table_name="ingestion_errors")
    op.drop_table("ingestion_errors")
    op.drop_index(op.f("ix_tags_name"), table_name="tags")
    op.drop_table("tags")
    op.drop_index(op.f("ix_organizations_normalized_name"), table_name="organizations")
    op.drop_table("organizations")
    op.drop_index(op.f("ix_ingestion_runs_status"), table_name="ingestion_runs")
    op.drop_index(op.f("ix_ingestion_runs_file_hash"), table_name="ingestion_runs")
    op.drop_table("ingestion_runs")
    op.drop_index(op.f("ix_authors_normalized_name"), table_name="authors")
    op.drop_table("authors")
    # ### end Alembic commands ###
